// <auto-generated />
using System;
using Mecanica_Automotiva.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mecanica_Automotiva.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20250902002845_AddSlugEndereco")]
    partial class AddSlugEndereco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgendaServico", b =>
                {
                    b.Property<Guid>("AgendarId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicosId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgendarId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("AgendaServico");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Queixa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("TempoServiçoTotal")
                        .HasColumnType("time(6)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QtdEnderecosCadastrados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EnderecoSlug")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosPeca.MarcaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarcaProdutos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.MarcaVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MarcaVeiculos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.ModeloVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CategoriaVeiculo")
                        .HasColumnType("int");

                    b.Property<Guid>("MarcaVeiculoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaVeiculoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ModeloVeiculos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarcaProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("int");

                    b.Property<Guid>("SubCategoriaProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VeiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaProdutoId");

                    b.HasIndex("SubCategoriaProdutoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProdutos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.ToTable("SubCategoriasProdutos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("ProdutoServico", b =>
                {
                    b.Property<Guid>("ProdutosId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProdutosId", "ServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ProdutoServico");
                });

            modelBuilder.Entity("AgendaServico", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Agenda", null)
                        .WithMany()
                        .HasForeignKey("AgendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Agenda", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosCliente.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Veiculo", "Veiculo")
                        .WithMany("Agendamentos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Endereco", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosCliente.Cliente", "Cliente")
                        .WithMany("Endereco")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.MarcaVeiculo", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Produto", null)
                        .WithMany("MarcasVeiculos")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.ModeloVeiculo", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.MarcaVeiculo", "MarcaVeiculo")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Produto", null)
                        .WithMany("ModelosVeiculos")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("MarcaVeiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produto", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosPeca.MarcaProduto", "MarcaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Produtos.SubCategoriaProduto", "SubCategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("SubCategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Veiculo", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VeiculoId");

                    b.Navigation("MarcaProduto");

                    b.Navigation("SubCategoriaProduto");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaProduto", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Produtos.CategoriaProduto", "CategoriaProduto")
                        .WithMany("SubCategoria")
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.MarcaVeiculo", "Marca")
                        .WithMany("Veiculo")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.ModeloVeiculo", "Modelo")
                        .WithMany("Veiculo")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("ProdutoServico", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Cliente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosPeca.MarcaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.MarcaVeiculo", b =>
                {
                    b.Navigation("Modelos");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.ModeloVeiculo", b =>
                {
                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produto", b =>
                {
                    b.Navigation("MarcasVeiculos");

                    b.Navigation("ModelosVeiculos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.CategoriaProduto", b =>
                {
                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
