// <auto-generated />
using System;
using Mecanica_Automotiva.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mecanica_Automotiva.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mecanica_Automotiva.Models.Agendar", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Queixa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("TempoServiçoTotal")
                        .HasColumnType("time(6)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("ClienteId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubCategoriaPecaID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("SubCategoriaPecaID");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.CategoriaPeca", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("CategoriasPecas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaPeca", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaPecaID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CategoriaPecaID");

                    b.ToTable("SubCategoriasPecas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AgendarID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("Duracao")
                        .HasColumnType("time(6)");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AgendarID");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Agendar", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosCliente.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Endereco", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosCliente.Cliente", "Cliente")
                        .WithMany("Endereco")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosVeiculo.Modelo", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Peca", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Servico", "Servico")
                        .WithMany("Pecas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Produtos.SubCategoriaPeca", "SubCategoriaPeca")
                        .WithMany("Pecas")
                        .HasForeignKey("SubCategoriaPecaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Veiculo", "Veiculo")
                        .WithMany("Pecas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("SubCategoriaPeca");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaPeca", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Produtos.CategoriaPeca", "CategoriaPeca")
                        .WithMany("SubCategoria")
                        .HasForeignKey("CategoriaPecaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPeca");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Servico", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.Agendar", "Agendar")
                        .WithMany("Servicos")
                        .HasForeignKey("AgendarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.Veiculo", "Veiculo")
                        .WithMany("Servico")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendar");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecanica_Automotiva.Models.DadosVeiculo.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Agendar", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.DadosCliente.Cliente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.CategoriaPeca", b =>
                {
                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Produtos.SubCategoriaPeca", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Servico", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("Mecanica_Automotiva.Models.Veiculo", b =>
                {
                    b.Navigation("Pecas");

                    b.Navigation("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
